#!/usr/bin/env python3
from generate_dotnet_exercises import dotnet_case

CASES = [
{
"id":"19","context":"um agregador de cotações que chama um provedor assíncrono para vários IDs.","situation":"Sob carga, o serviço bloqueia threads e ignora cancelamento. Faça I/O realmente assíncrono e limite chamadas simultâneas ao orçamento configurado.","expected":"`FetchAllAsync` preserva a ordem de IDs, propaga cancelamento e nunca ultrapassa `maxConcurrency`.","intent":"Avaliar async/await, concorrência limitada e propagação de cancelamento.","cause":"uso de `.Result` em loop sequencial.","trap":"envolver I/O em `Task.Run` ou lançar todas as tarefas sem limite.","notes":"A referência usa `SemaphoreSlim`, `await` e escreve cada resultado em sua posição original.",
"criteria":[("C01","mínimo",3,"caminho não bloqueia Task sincronamente"),("C02","mínimo",2,"resultados preservam a ordem"),("C03","mínimo",2,"concorrência respeita o limite"),("C04","intermediário",2,"cancelamento chega ao provedor"),("C05","desejado",1,"lista vazia retorna imediatamente")],
"broken":'''namespace Challenge;public interface IRemote{Task<string> FetchAsync(string id,CancellationToken ct);}public sealed class Aggregator(IRemote remote,int maxConcurrency=4){public int ConfiguredConcurrency=>maxConcurrency;public Task<IReadOnlyList<string>> FetchAllAsync(IReadOnlyList<string> ids,CancellationToken ct=default){var r=new List<string>();foreach(var id in ids)r.Add(remote.FetchAsync(id,ct).Result);return Task.FromResult<IReadOnlyList<string>>(r);}}''',
"solution":'''namespace Challenge;public interface IRemote{Task<string> FetchAsync(string id,CancellationToken ct);}public sealed class Aggregator(IRemote remote,int maxConcurrency=4){public async Task<IReadOnlyList<string>> FetchAllAsync(IReadOnlyList<string> ids,CancellationToken ct=default){using var gate=new SemaphoreSlim(maxConcurrency);var output=new string[ids.Count];var tasks=ids.Select(async(id,i)=>{await gate.WaitAsync(ct);try{output[i]=await remote.FetchAsync(id,ct);}finally{gate.Release();}});await Task.WhenAll(tasks);return output;}}''',
"public":'''using Challenge;var r=await new Aggregator(new F()).FetchAllAsync(["a"]);if(r.Single()!="a")throw new Exception();Console.WriteLine("Public tests passed");class F:IRemote{public Task<string> FetchAsync(string id,CancellationToken ct)=>Task.FromResult(id);}''',
"hidden":'''using Challenge;void P(string id,bool ok)=>Console.WriteLine($"{id}|{(ok?"pass":"fail")}");P("C01",true);var f=new F();var r=await new Aggregator(f,2).FetchAllAsync(["a","b","c"]);P("C02",r.SequenceEqual(["a","b","c"]));P("C03",f.Peak<=2);var cts=new CancellationTokenSource();cts.Cancel();try{await new Aggregator(new F(),1).FetchAllAsync(["x"],cts.Token);P("C04",false);}catch(OperationCanceledException){P("C04",true);}P("C05",(await new Aggregator(new F()).FetchAllAsync([])).Count==0);class F:IRemote{int active;public int Peak;public async Task<string> FetchAsync(string id,CancellationToken ct){var n=Interlocked.Increment(ref active);Peak=Math.Max(Peak,n);try{await Task.Delay(20,ct);return id;}finally{Interlocked.Decrement(ref active);}}}''',
"static":[{"id":"C01","forbid":"\\.Result\\b|\\.Wait\\s*\\(|GetAwaiter\\(\\)\\.GetResult"}]
},
{
"id":"20","context":"o resgate de cupons de uso único por múltiplas instâncias que compartilham o mesmo armazenamento em memória do exercício.","situation":"Requisições simultâneas conseguem confirmar o mesmo cupom. Faça a verificação e a gravação atômicas no estado compartilhado.","expected":"Exatamente um resgate retorna sucesso e auditoria/saldo permanecem consistentes.","intent":"Avaliar race condition, atomicidade e diferença entre lock local e recurso compartilhado.","cause":"check-then-act sem sincronização.","trap":"proteger apenas um contador da instância do serviço.","notes":"A referência usa o gate pertencente ao armazenamento compartilhado para serializar a transição.",
"criteria":[("C01","mínimo",3,"primeiro resgate vence"),("C02","mínimo",3,"somente um resgate concorrente vence"),("C03","mínimo",2,"auditoria contém um evento"),("C04","intermediário",1,"duas instâncias mantêm a garantia"),("C05","desejado",1,"cupom inexistente não altera estado")],
"broken":'''namespace Challenge;public sealed class CouponStore{public HashSet<string> Valid=new();public HashSet<string> Used=new();public List<string> Audit=new();}public sealed class CouponService(CouponStore store){public bool Redeem(string code){if(!store.Valid.Contains(code)||store.Used.Contains(code))return false;Thread.Yield();store.Used.Add(code);store.Audit.Add(code);return true;}}''',
"solution":'''namespace Challenge;public sealed class CouponStore{public HashSet<string> Valid=new();public HashSet<string> Used=new();public List<string> Audit=new();internal object Gate=new();}public sealed class CouponService(CouponStore store){public bool Redeem(string code){lock(store.Gate){if(!store.Valid.Contains(code)||!store.Used.Add(code))return false;store.Audit.Add(code);return true;}}}''',
"public":'''using Challenge;var d=new CouponStore();d.Valid.Add("A");if(!new CouponService(d).Redeem("A"))throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}C("C01",()=>{var d=new CouponStore();d.Valid.Add("A");return new CouponService(d).Redeem("A");});C("C02",()=>{var d=new CouponStore();d.Valid.Add("A");var s=new CouponService(d);var wins=0;Parallel.For(0,100,_=>{if(s.Redeem("A"))Interlocked.Increment(ref wins);});return wins==1;});C("C03",()=>{var d=new CouponStore();d.Valid.Add("A");var s=new CouponService(d);Parallel.For(0,20,_=>s.Redeem("A"));return d.Audit.Count==1;});C("C04",()=>{var d=new CouponStore();d.Valid.Add("A");var a=new CouponService(d);var b=new CouponService(d);return new[]{Task.Run(()=>a.Redeem("A")),Task.Run(()=>b.Redeem("A"))}.Count(x=>x.Result)==1;});C("C05",()=>{var d=new CouponStore();return !new CouponService(d).Redeem("X")&&d.Audit.Count==0;});'''
},
{
"id":"21","context":"um consumidor de eventos de faturamento sujeito a redelivery e execução por duas instâncias.","situation":"A mesma chave de mensagem deve produzir uma única fatura. Se ocorrer falha antes do commit lógico, a nova entrega deve poder concluir sem duplicação.","expected":"A deduplicação deve residir no armazenamento compartilhado e efeito/marcação devem ser atômicos no modelo fornecido.","intent":"Avaliar idempotência distribuída e fronteira transacional.","cause":"cada consumidor mantém seu próprio HashSet e grava o efeito antes de marcar a mensagem.","trap":"deduplicar apenas em memória por instância ou marcar antes do efeito.","notes":"A referência usa o gate do InboxStore e reverte a lista se a simulação falha antes da marcação.",
"criteria":[("C01","mínimo",3,"redelivery cria uma fatura"),("C02","mínimo",3,"duas instâncias compartilham deduplicação"),("C03","mínimo",2,"falha permite retry sem duplicação"),("C04","intermediário",1,"chaves distintas geram efeitos distintos"),("C05","desejado",1,"mensagem já concluída retorna sucesso idempotente")],
"broken":'''namespace Challenge;public sealed class InboxStore{public HashSet<string> Processed=new();public List<string> Invoices=new();}public sealed class Consumer(InboxStore store){readonly HashSet<string> local=new();public bool Handle(string id,bool fail=false){if(!local.Add(id))return true;store.Invoices.Add(id);if(fail)throw new InvalidOperationException();store.Processed.Add(id);return true;}}''',
"solution":'''namespace Challenge;public sealed class InboxStore{public HashSet<string> Processed=new();public List<string> Invoices=new();internal object Gate=new();}public sealed class Consumer(InboxStore store){public bool Handle(string id,bool fail=false){lock(store.Gate){if(store.Processed.Contains(id))return true;store.Invoices.Add(id);try{if(fail)throw new InvalidOperationException();store.Processed.Add(id);return true;}catch{store.Invoices.Remove(id);throw;}}}}''',
"public":'''using Challenge;var d=new InboxStore();new Consumer(d).Handle("1");if(d.Invoices.Count!=1)throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}C("C01",()=>{var d=new InboxStore();var s=new Consumer(d);s.Handle("1");s.Handle("1");return d.Invoices.Count==1;});C("C02",()=>{var d=new InboxStore();new Consumer(d).Handle("1");new Consumer(d).Handle("1");return d.Invoices.Count==1;});C("C03",()=>{var d=new InboxStore();try{new Consumer(d).Handle("1",true);}catch{}new Consumer(d).Handle("1");return d.Invoices.Count==1&&d.Processed.Contains("1");});C("C04",()=>{var d=new InboxStore();var s=new Consumer(d);s.Handle("1");s.Handle("2");return d.Invoices.Count==2;});C("C05",()=>{var d=new InboxStore();var s=new Consumer(d);return s.Handle("1")&&s.Handle("1");});'''
},
{
"id":"22","context":"uma API multi-tenant de pedidos. A identidade autenticada é passada separadamente do payload.","situation":"Usuários conseguem ler, alterar ou cancelar pedidos de outro cliente ao trocar o ID. Aplique autorização por recurso em todas as operações.","expected":"Somente o proprietário pode operar; a resposta para recurso inexistente ou alheio deve seguir a política `NotFound`.","intent":"Avaliar Broken Object Level Authorization e centralização de política.","cause":"somente a existência do pedido é verificada.","trap":"confiar em customerId do request ou proteger apenas leitura.","notes":"A referência resolve pedido e proprietário em uma função comum usada pelos três caminhos.",
"criteria":[("C01","mínimo",3,"leitura cruzada é negada"),("C02","mínimo",3,"alteração e cancelamento cruzados são negados"),("C03","mínimo",2,"proprietário mantém acesso"),("C04","intermediário",1,"recurso alheio não revela existência"),("C05","desejado",1,"política é aplicada aos três métodos")],
"broken":'''namespace Challenge;public record Order(string Id,string Owner,string Status,string Note);public sealed class Orders(Dictionary<string,Order> data){public Order? Get(string actor,string id)=>data.GetValueOrDefault(id);public string Update(string actor,string id,string note){if(!data.TryGetValue(id,out var o))return "NotFound";data[id]=o with{Note=note};return "Ok";}public string Cancel(string actor,string id){if(!data.TryGetValue(id,out var o))return "NotFound";data[id]=o with{Status="Cancelled"};return "Ok";}}''',
"solution":'''namespace Challenge;public record Order(string Id,string Owner,string Status,string Note);public sealed class Orders(Dictionary<string,Order> data){Order? Owned(string actor,string id)=>data.TryGetValue(id,out var o)&&o.Owner==actor?o:null;public Order? Get(string actor,string id)=>Owned(actor,id);public string Update(string actor,string id,string note){var o=Owned(actor,id);if(o is null)return "NotFound";data[id]=o with{Note=note};return "Ok";}public string Cancel(string actor,string id){var o=Owned(actor,id);if(o is null)return "NotFound";data[id]=o with{Status="Cancelled"};return "Ok";}}''',
"public":'''using Challenge;var d=new Dictionary<string,Order>{{"1",new("1","a","New","")}};if(new Orders(d).Get("a","1") is null)throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}Dictionary<string,Order>D()=>new(){{"1",new("1","a","New","")}};C("C01",()=>new Orders(D()).Get("b","1") is null);C("C02",()=>{var d=D();var s=new Orders(d);return s.Update("b","1","x")=="NotFound"&&s.Cancel("b","1")=="NotFound"&&d["1"].Status=="New";});C("C03",()=>{var d=D();var s=new Orders(d);return s.Update("a","1","x")=="Ok"&&s.Cancel("a","1")=="Ok";});C("C04",()=>new Orders(D()).Update("b","1","x")==new Orders(D()).Update("b","missing","x"));C("C05",()=>{var d=D();var s=new Orders(d);return s.Get("b","1") is null&&s.Update("b","1","x")=="NotFound"&&s.Cancel("b","1")=="NotFound";});'''
},
{
"id":"23","context":"um construtor de consulta para busca administrativa. O executor aceita SQL e parâmetros nomeados.","situation":"Elimine injeção em filtro e ordenação. Valores devem ser parametrizados; coluna e direção só podem vir de allowlists.","expected":"Campos permitidos são `name`, `createdAt`; direções `asc`, `desc`. Entrada inválida gera `ArgumentException`.","intent":"Avaliar SQL injection em valores e identificadores.","cause":"todas as entradas são interpoladas diretamente.","trap":"parametrizar o filtro e ainda interpolar sort arbitrário.","notes":"A referência mapeia aliases públicos para colunas constantes e usa `@filter`.",
"criteria":[("C01","mínimo",3,"filtro usa parâmetro"),("C02","mínimo",3,"coluna possui allowlist"),("C03","mínimo",2,"direção possui allowlist"),("C04","intermediário",1,"entrada inválida não inclui detalhe SQL"),("C05","desejado",1,"busca legítima preserva contrato")],
"broken":'''namespace Challenge;public record Query(string Sql,IReadOnlyDictionary<string,object> Parameters);public static class SearchQuery{public static Query Build(string filter,string sort,string direction)=>new($"SELECT id,name FROM products WHERE name ILIKE '%{filter}%' ORDER BY {sort} {direction}",new Dictionary<string,object>()); }''',
"solution":'''namespace Challenge;public record Query(string Sql,IReadOnlyDictionary<string,object> Parameters);public static class SearchQuery{public static Query Build(string filter,string sort,string direction){var column=sort switch{"name"=>"name","createdAt"=>"created_at",_=>throw new ArgumentException("Unsupported sort")};var dir=direction.ToLowerInvariant() switch{"asc"=>"ASC","desc"=>"DESC",_=>throw new ArgumentException("Unsupported direction")};return new($"SELECT id,name FROM products WHERE name ILIKE @filter ORDER BY {column} {dir}",new Dictionary<string,object>{{"filter",$"%{filter}%"}});}}''',
"public":'''using Challenge;var q=SearchQuery.Build("apple","name","asc");if(!q.Sql.Contains("SELECT id,name FROM products"))throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}C("C01",()=>{var q=SearchQuery.Build("x' OR 1=1 --","name","asc");return !q.Sql.Contains("OR 1=1")&&q.Parameters.Values.Cast<string>().Single().Contains("OR 1=1");});C("C02",()=>{try{SearchQuery.Build("x","name; DROP TABLE x","asc");return false;}catch(ArgumentException){return true;}});C("C03",()=>{try{SearchQuery.Build("x","name","asc; DROP");return false;}catch(ArgumentException){return true;}});C("C04",()=>{try{SearchQuery.Build("x","bad","asc");return false;}catch(ArgumentException e){return !e.Message.Contains("SELECT");}});C("C05",()=>SearchQuery.Build("a","createdAt","DESC").Sql.EndsWith("created_at DESC"));'''
},
{
"id":"24","context":"o recebimento local de comprovantes PDF e PNG. O método retorna o caminho armazenado ou um código de rejeição.","situation":"Proteja contra traversal, tamanho excessivo, tipo forjado e arquivos parciais. Não use o nome do cliente como caminho final.","expected":"Leia no máximo `maxBytes+1`, verifique assinatura de conteúdo e grave apenas arquivos aceitos sob `root`.","intent":"Avaliar segurança de upload e uso seguro de filesystem.","cause":"o nome e MIME declarados são confiados e o stream inteiro é copiado sem limite.","trap":"validar somente extensão ou `Content-Type`.","notes":"A referência limita leitura, verifica magic bytes, cria nome aleatório e só então grava.",
"criteria":[("C01","mínimo",3,"traversal não escapa do root"),("C02","mínimo",3,"limite é aplicado durante leitura"),("C03","mínimo",2,"conteúdo incompatível é rejeitado"),("C04","intermediário",1,"nomes armazenados não colidem"),("C05","desejado",1,"rejeição não deixa arquivo parcial")],
"broken":'''namespace Challenge;public record UploadResult(bool Accepted,string? Path,string? Error);public static class Uploads{public static UploadResult Save(string root,string fileName,string contentType,Stream input,int maxBytes){Directory.CreateDirectory(root);var path=System.IO.Path.Combine(root,fileName);using var f=File.Create(path);input.CopyTo(f);return new(true,path,null);}}''',
"solution":'''namespace Challenge;public record UploadResult(bool Accepted,string? Path,string? Error);public static class Uploads{public static UploadResult Save(string root,string fileName,string contentType,Stream input,int maxBytes){Directory.CreateDirectory(root);using var data=new MemoryStream();var buffer=new byte[8192];int total=0,n;while((n=input.Read(buffer,0,Math.Min(buffer.Length,maxBytes+1-total)))>0){total+=n;if(total>maxBytes)return new(false,null,"too_large");data.Write(buffer,0,n);}var b=data.ToArray();var ext=b.Length>=5&&b.AsSpan(0,5).SequenceEqual("%PDF-"u8)?".pdf":b.Length>=8&&b.AsSpan(0,8).SequenceEqual(new byte[]{137,80,78,71,13,10,26,10})?".png":null;if(ext is null)return new(false,null,"invalid_type");var path=System.IO.Path.Combine(System.IO.Path.GetFullPath(root),Guid.NewGuid().ToString("N")+ext);File.WriteAllBytes(path,b);return new(true,path,null);}}''',
"public":'''using Challenge;var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString());var r=Uploads.Save(root,"a.pdf","application/pdf",new MemoryStream("%PDF-x"u8.ToArray()),100);if(!r.Accepted)throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}string Root()=>Path.Combine(Path.GetTempPath(),"up-"+Guid.NewGuid());C("C01",()=>{var root=Root();var r=Uploads.Save(root,"../evil.pdf","application/pdf",new MemoryStream("%PDF-x"u8.ToArray()),20);return r.Path is not null&&Path.GetFullPath(r.Path).StartsWith(Path.GetFullPath(root));});C("C02",()=>{var root=Root();var r=Uploads.Save(root,"x.pdf","application/pdf",new MemoryStream(new byte[100]),10);return !r.Accepted&&(!Directory.Exists(root)||!Directory.EnumerateFiles(root).Any());});C("C03",()=>!Uploads.Save(Root(),"x.pdf","application/pdf",new MemoryStream("hello"u8.ToArray()),20).Accepted);C("C04",()=>{var root=Root();var a=Uploads.Save(root,"x.pdf","application/pdf",new MemoryStream("%PDF-a"u8.ToArray()),20);var b=Uploads.Save(root,"x.pdf","application/pdf",new MemoryStream("%PDF-b"u8.ToArray()),20);return a.Path!=b.Path;});C("C05",()=>{var root=Root();Uploads.Save(root,"x","x",new MemoryStream(new byte[30]),10);return !Directory.EnumerateFiles(root).Any();});'''
},
{
"id":"25","context":"um endpoint de webhooks assinado por HMAC-SHA256. O cabeçalho contém o hexadecimal minúsculo da assinatura do corpo bruto.","situation":"Valide a assinatura em tempo constante e processe cada `id` JSON apenas uma vez.","expected":"Corpo alterado ou assinatura inválida é rejeitado; repetição válida responde sucesso idempotente sem novo efeito.","intent":"Avaliar integração autenticada, bytes brutos e idempotência.","cause":"a assinatura é calculada sobre JSON normalizado e eventos repetidos são sempre aplicados.","trap":"desserializar antes de verificar ou comparar segredos com igualdade comum.","notes":"A referência calcula HMAC sobre os bytes recebidos, usa FixedTimeEquals e trava a store compartilhada.",
"criteria":[("C01","mínimo",3,"assinatura sobre corpo bruto é aceita"),("C02","mínimo",3,"assinatura inválida é rejeitada"),("C03","mínimo",2,"evento repetido não duplica efeito"),("C04","intermediário",1,"JSON inválido assinado é rejeitado com segurança"),("C05","desejado",1,"comparação usa tempo constante")],
"broken":'''using System.Security.Cryptography;using System.Text;using System.Text.Json;namespace Challenge;public sealed class WebhookStore{public HashSet<string> Seen=new();public List<string> Effects=new();}public sealed class Receiver(byte[] secret,WebhookStore store){public bool Handle(byte[] raw,string signature){using var doc=JsonDocument.Parse(raw);var normalized=JsonSerializer.SerializeToUtf8Bytes(doc.RootElement);var expected=Convert.ToHexString(HMACSHA256.HashData(secret,normalized)).ToLowerInvariant();if(expected!=signature)return false;var id=doc.RootElement.GetProperty("id").GetString()!;store.Seen.Add(id);store.Effects.Add(id);return true;}}''',
"solution":'''using System.Security.Cryptography;using System.Text.Json;namespace Challenge;public sealed class WebhookStore{public HashSet<string> Seen=new();public List<string> Effects=new();internal object Gate=new();}public sealed class Receiver(byte[] secret,WebhookStore store){public bool Handle(byte[] raw,string signature){byte[] provided;try{provided=Convert.FromHexString(signature);}catch{return false;}var expected=HMACSHA256.HashData(secret,raw);if(provided.Length!=expected.Length||!CryptographicOperations.FixedTimeEquals(provided,expected))return false;string? id;try{using var doc=JsonDocument.Parse(raw);id=doc.RootElement.GetProperty("id").GetString();}catch{return false;}if(string.IsNullOrWhiteSpace(id))return false;lock(store.Gate){if(!store.Seen.Add(id))return true;store.Effects.Add(id);return true;}}}''',
"public":'''using Challenge;using System.Security.Cryptography;using System.Text;var secret="s"u8.ToArray();var q=(char)34;var raw=Encoding.UTF8.GetBytes($"{{{q}id{q}:{q}1{q}}}");var sig=Convert.ToHexString(HMACSHA256.HashData(secret,raw)).ToLowerInvariant();if(!new Receiver(secret,new()).Handle(raw,sig))throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;using System.Security.Cryptography;using System.Text;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}var key="secret"u8.ToArray();string Sig(byte[] x)=>Convert.ToHexString(HMACSHA256.HashData(key,x)).ToLowerInvariant();var q=(char)34;var raw=Encoding.UTF8.GetBytes($"{{ {q}id{q} : {q}a{q} }}");C("C01",()=>new Receiver(key,new()).Handle(raw,Sig(raw)));C("C02",()=>!new Receiver(key,new()).Handle(raw,new string('0',64)));C("C03",()=>{var d=new WebhookStore();var s=new Receiver(key,d);s.Handle(raw,Sig(raw));s.Handle(raw,Sig(raw));return d.Effects.Count==1;});C("C04",()=>{var x="no-json"u8.ToArray();return !new Receiver(key,new()).Handle(x,Sig(x));});C("C05",()=>true);''',
"static":[{"id":"C05","require":"FixedTimeEquals"}]
},
{
"id":"26","context":"um cliente de pagamentos com provedor fake. Resultados são `Success`, `Transient` ou `Permanent`.","situation":"Repita somente falhas transitórias, no máximo três tentativas, sempre com a mesma chave idempotente. Cancelamento deve parar imediatamente e falhas consecutivas devem abrir o breaker da instância.","expected":"Depois de duas operações esgotadas, uma terceira retorna `CircuitOpen` sem chamar o provedor.","intent":"Avaliar retry seguro, idempotência, cancelamento e circuit breaker.","cause":"toda falha é repetida com uma nova chave e não existe breaker.","trap":"repetir POST com GUID novo ou retry de erro permanente.","notes":"A referência preserva a chave, limita tentativas e abre o circuito após duas operações transientes esgotadas.",
"criteria":[("C01","mínimo",3,"somente transientes são repetidas"),("C02","mínimo",3,"tentativas preservam chave idempotente"),("C03","mínimo",2,"máximo de três tentativas"),("C04","intermediário",1,"cancelamento interrompe tentativas"),("C05","desejado",1,"breaker evita chamadas após limiar")],
"broken":'''namespace Challenge;public enum PaymentStatus{Success,Transient,Permanent,CircuitOpen}public interface IPaymentProvider{Task<PaymentStatus> SendAsync(string key,CancellationToken ct);}public sealed class PaymentClient(IPaymentProvider provider){public async Task<PaymentStatus> PayAsync(string key,CancellationToken ct=default){PaymentStatus s=PaymentStatus.Transient;for(int i=0;i<3&&s!=PaymentStatus.Success;i++)s=await provider.SendAsync(Guid.NewGuid().ToString(),ct);return s;}}''',
"solution":'''namespace Challenge;public enum PaymentStatus{Success,Transient,Permanent,CircuitOpen}public interface IPaymentProvider{Task<PaymentStatus> SendAsync(string key,CancellationToken ct);}public sealed class PaymentClient(IPaymentProvider provider){int exhausted;public async Task<PaymentStatus> PayAsync(string key,CancellationToken ct=default){ct.ThrowIfCancellationRequested();if(Volatile.Read(ref exhausted)>=2)return PaymentStatus.CircuitOpen;for(int i=0;i<3;i++){ct.ThrowIfCancellationRequested();var s=await provider.SendAsync(key,ct);if(s==PaymentStatus.Success){Interlocked.Exchange(ref exhausted,0);return s;}if(s==PaymentStatus.Permanent)return s;}Interlocked.Increment(ref exhausted);return PaymentStatus.Transient;}}''',
"public":'''using Challenge;var f=new F();if(await new PaymentClient(f).PayAsync("k")!=PaymentStatus.Success)throw new Exception();Console.WriteLine("Public tests passed");class F:IPaymentProvider{public Task<PaymentStatus> SendAsync(string k,CancellationToken c)=>Task.FromResult(PaymentStatus.Success);}''',
"hidden":'''using Challenge;void P(string id,bool ok)=>Console.WriteLine($"{id}|{(ok?"pass":"fail")}");var a=new F(PaymentStatus.Permanent);await new PaymentClient(a).PayAsync("k");P("C01",a.Keys.Count==1);var b=new F(PaymentStatus.Transient);await new PaymentClient(b).PayAsync("same");P("C02",b.Keys.Distinct().Single()=="same");P("C03",b.Keys.Count==3);var cts=new CancellationTokenSource();cts.Cancel();try{await new PaymentClient(new F(PaymentStatus.Transient)).PayAsync("k",cts.Token);P("C04",false);}catch(OperationCanceledException){P("C04",true);}var d=new F(PaymentStatus.Transient);var client=new PaymentClient(d);await client.PayAsync("1");await client.PayAsync("2");var before=d.Keys.Count;P("C05",await client.PayAsync("3")==PaymentStatus.CircuitOpen&&d.Keys.Count==before);class F(PaymentStatus value):IPaymentProvider{public List<string> Keys=[];public Task<PaymentStatus> SendAsync(string key,CancellationToken ct){ct.ThrowIfCancellationRequested();Keys.Add(key);return Task.FromResult(value);}}'''
},
{
"id":"27","context":"um novo serviço de encurtamento de URLs. O repositório entrega os contratos `ILinkStore` e `ICodeSource`; a implementação do serviço começa vazia.","situation":"Implemente criação e resolução. Aceite somente HTTP/HTTPS absolutos, trate colisões tentando outro código e garanta unicidade com instâncias que compartilham a store.","expected":"Códigos já existentes não podem ser sobrescritos; `Resolve` retorna null quando ausente.","intent":"Avaliar criação de componente do zero, contrato, validação e concorrência sem prescrever arquitetura.","cause":"métodos lançam `NotImplementedException`.","trap":"validar URL apenas por prefixo ou sobrescrever colisão.","notes":"A referência valida `Uri`, pede códigos até `TryAdd` vencer e usa a atomicidade do repositório.",
"criteria":[("C01","mínimo",3,"criar e resolver preserva URL"),("C02","mínimo",2,"somente HTTP/HTTPS absoluto é aceito"),("C03","mínimo",2,"colisão não sobrescreve link"),("C04","intermediário",2,"duas instâncias geram códigos únicos"),("C05","desejado",1,"código ausente retorna null")],
"broken":'''namespace Challenge;public interface ICodeSource{string Next();}public interface ILinkStore{bool TryAdd(string code,string url);string? Get(string code);}public sealed class LinkService(ILinkStore store,ICodeSource codes){public ILinkStore Store=>store;public ICodeSource Codes=>codes;public string Create(string url)=>throw new NotImplementedException();public string? Resolve(string code)=>throw new NotImplementedException();}public sealed class MemoryLinkStore:ILinkStore{readonly Dictionary<string,string>d=new();readonly object gate=new();public bool TryAdd(string c,string u){lock(gate){return d.TryAdd(c,u);}}public string? Get(string c){lock(gate){return d.GetValueOrDefault(c);}}}''',
"solution":'''namespace Challenge;public interface ICodeSource{string Next();}public interface ILinkStore{bool TryAdd(string code,string url);string? Get(string code);}public sealed class LinkService(ILinkStore store,ICodeSource codes){public string Create(string url){if(!Uri.TryCreate(url,UriKind.Absolute,out var uri)||(uri.Scheme!="http"&&uri.Scheme!="https"))throw new ArgumentException("Invalid URL",nameof(url));for(int i=0;i<100;i++){var c=codes.Next();if(!string.IsNullOrWhiteSpace(c)&&store.TryAdd(c,url))return c;}throw new InvalidOperationException("Could not allocate code");}public string? Resolve(string code)=>store.Get(code);}public sealed class MemoryLinkStore:ILinkStore{readonly Dictionary<string,string>d=new();readonly object gate=new();public bool TryAdd(string c,string u){lock(gate){return d.TryAdd(c,u);}}public string? Get(string c){lock(gate){return d.GetValueOrDefault(c);}}}''',
"public":'''using Challenge;Console.WriteLine("Project compiles; implement the challenge and add tests.");''',
"hidden":'''using Challenge;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}C("C01",()=>{var s=new LinkService(new MemoryLinkStore(),new Codes("a"));return s.Resolve(s.Create("https://example.com/x"))=="https://example.com/x";});C("C02",()=>{try{new LinkService(new MemoryLinkStore(),new Codes("a")).Create("javascript:alert(1)");return false;}catch(ArgumentException){return true;}});C("C03",()=>{var d=new MemoryLinkStore();d.TryAdd("x","https://old");var s=new LinkService(d,new Codes("x","y"));return s.Create("https://new")=="y"&&d.Get("x")=="https://old";});C("C04",()=>{var d=new MemoryLinkStore();var a=new LinkService(d,new Codes("a","b"));var b=new LinkService(d,new Codes("a","c"));return Task.WhenAll(Task.Run(()=>a.Create("https://a")),Task.Run(()=>b.Create("https://b"))).Result.Distinct().Count()==2;});C("C05",()=>new LinkService(new MemoryLinkStore(),new Codes("a")).Resolve("missing") is null);class Codes(params string[] values):ICodeSource{int i;public string Next()=>values[Math.Min(Interlocked.Increment(ref i)-1,values.Length-1)];}'''
}
]

if __name__ == "__main__":
    for case in CASES:
        dotnet_case(case)
    print(f"Generated {len(CASES)} .NET exercises")
