#!/usr/bin/env python3
from generate_dotnet_exercises import dotnet_case

CASES = [
{
"id":"12","context":"o núcleo de agendamento de uma clínica internacional. Instantes são persistidos com offset e exibidos no fuso IANA/Windows fornecido.",
"situation":"Consultas aparecem no dia errado quando o usuário não está em UTC. Calcule a data local e os limites UTC de um dia civil no fuso escolhido.",
"expected":"Use `TimeZoneInfo` e preserve instantes; não dependa do fuso configurado na máquina.",
"intent":"Avaliar modelagem de tempo, conversão de fuso e testes determinísticos.","cause":"a implementação usa `.Date` sobre o instante original e soma 24 horas em UTC.","trap":"aplicar offset manual duas vezes ou usar `DateTime.Now`.","notes":"A referência converte o instante pelo fuso e converte cada meia-noite local para UTC separadamente.",
"criteria":[("C01","mínimo",3,"data local usa o fuso informado"),("C02","mínimo",2,"instante não é alterado"),("C03","mínimo",2,"limites do dia são convertidos para UTC"),("C04","intermediário",2,"dia de horário de verão pode ter duração diferente de 24h"),("C05","desejado",1,"resultado independe do fuso da máquina")],
"broken":'''namespace Challenge;public static class Scheduling{public static DateOnly LocalDate(DateTimeOffset instant,TimeZoneInfo zone)=>DateOnly.FromDateTime(instant.Date);public static (DateTimeOffset Start,DateTimeOffset End) UtcDay(DateOnly day,TimeZoneInfo zone){var s=new DateTimeOffset(day.ToDateTime(TimeOnly.MinValue),TimeSpan.Zero);return(s,s.AddDays(1));}}''',
"solution":'''namespace Challenge;public static class Scheduling{public static DateOnly LocalDate(DateTimeOffset instant,TimeZoneInfo zone)=>DateOnly.FromDateTime(TimeZoneInfo.ConvertTime(instant,zone).DateTime);public static (DateTimeOffset Start,DateTimeOffset End) UtcDay(DateOnly day,TimeZoneInfo zone){var local=DateTime.SpecifyKind(day.ToDateTime(TimeOnly.MinValue),DateTimeKind.Unspecified);var next=DateTime.SpecifyKind(day.AddDays(1).ToDateTime(TimeOnly.MinValue),DateTimeKind.Unspecified);return(new DateTimeOffset(TimeZoneInfo.ConvertTimeToUtc(local,zone)),new DateTimeOffset(TimeZoneInfo.ConvertTimeToUtc(next,zone)));}}''',
"public":'''using Challenge;var z=TimeZoneInfo.Utc;var t=DateTimeOffset.Parse("2025-01-02T03:00:00Z");if(Scheduling.LocalDate(t,z)!=new DateOnly(2025,1,2))throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}var z=TimeZoneInfo.FindSystemTimeZoneById("America/New_York");var t=DateTimeOffset.Parse("2025-01-02T02:00:00Z");C("C01",()=>Scheduling.LocalDate(t,z)==new DateOnly(2025,1,1));C("C02",()=>t==DateTimeOffset.Parse("2025-01-02T02:00:00Z"));C("C03",()=>Scheduling.UtcDay(new(2025,1,1),z).Start==DateTimeOffset.Parse("2025-01-01T05:00:00Z"));C("C04",()=>{var x=Scheduling.UtcDay(new(2025,3,9),z);return x.End-x.Start==TimeSpan.FromHours(23);});C("C05",()=>Scheduling.LocalDate(t,z)==new DateOnly(2025,1,1));'''
},
{
"id":"13","context":"o cálculo de uma fatura com quantidades fracionárias. A política arredonda cada linha após desconto e o imposto sobre a soma das linhas.",
"situation":"Totais divergem por centavos. Elimine ponto flutuante binário e implemente arredondamento monetário `AwayFromZero` nos limites descritos.",
"expected":"`Invoice.Total` deve ser simétrico para estornos e produzir duas casas decimais.",
"intent":"Avaliar precisão monetária e tradução exata de regra contábil.","cause":"a implementação converte para `double` e arredonda apenas o total final.","trap":"apenas trocar o tipo sem corrigir a ordem de arredondamento.","notes":"A referência calcula e arredonda cada linha em decimal, soma e então calcula/arredonda o imposto.",
"criteria":[("C01","mínimo",3,"cada linha é arredondada antes da soma"),("C02","mínimo",2,"cálculo não perde precisão decimal"),("C03","mínimo",2,"imposto usa a soma líquida"),("C04","intermediário",2,"estorno é simétrico"),("C05","desejado",1,"meio centavo usa AwayFromZero")],
"broken":'''namespace Challenge;public record Line(decimal UnitPrice,decimal Quantity,decimal Discount);public static class Invoice{public static decimal Total(IEnumerable<Line> lines,decimal tax){double sum=lines.Sum(x=>(double)(x.UnitPrice*x.Quantity*(1-x.Discount)));return (decimal)Math.Round(sum*(1+(double)tax),2);}}''',
"solution":'''namespace Challenge;public record Line(decimal UnitPrice,decimal Quantity,decimal Discount);public static class Invoice{static decimal Money(decimal x)=>Math.Round(x,2,MidpointRounding.AwayFromZero);public static decimal Total(IEnumerable<Line> lines,decimal tax){var net=lines.Sum(x=>Money(x.UnitPrice*x.Quantity*(1-x.Discount)));return Money(net+Money(net*tax));}}''',
"public":'''using Challenge;if(Invoice.Total([new(10m,2m,0m)],.1m)!=22m)throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}C("C01",()=>Invoice.Total([new(.025m,1,0),new(.025m,1,0)],0)==.06m);C("C02",()=>Invoice.Total([new(.1m,3,0)],0)==.30m);C("C03",()=>Invoice.Total([new(1.005m,1,0)],.10m)==1.11m);C("C04",()=>Invoice.Total([new(-1.005m,1,0)],0)==-1.01m);C("C05",()=>Invoice.Total([new(.005m,1,0)],0)==.01m);'''
},
{
"id":"14","context":"um motor legado de promoções. Regras devem ser isoladas e aplicadas em ordem explícita sobre o valor corrente.",
"situation":"Refatore o motor para aceitar regras substituíveis e testáveis, preservando a ordem recebida e impedindo total negativo.",
"expected":"A adição de uma nova implementação de `IPromotion` não deve exigir alteração no motor.",
"intent":"Avaliar refatoração protegida, Strategy e Open/Closed sem overengineering.","cause":"o motor ignora as estratégias recebidas e contém condicionais fixas.","trap":"mudar a precedência ou aplicar todas as regras sobre o subtotal original.","notes":"A referência encadeia as estratégias na ordem fornecida e limita o resultado final a zero.",
"criteria":[("C01","mínimo",3,"regras recebidas são executadas"),("C02","mínimo",2,"ordem de aplicação é preservada"),("C03","mínimo",2,"total nunca fica negativo"),("C04","intermediário",2,"nova regra não requer mudança no motor"),("C05","desejado",1,"lista vazia preserva subtotal")],
"broken":'''namespace Challenge;public record Cart(decimal Subtotal,bool Vip,string Coupon);public interface IPromotion{decimal Apply(Cart cart,decimal current);}public sealed class PricingEngine(IEnumerable<IPromotion> rules){public int ConfiguredRules=>rules.Count();public decimal Total(Cart cart){var value=cart.Subtotal;if(cart.Vip)value*=.9m;if(cart.Coupon=="SAVE5")value-=5;return value;}}''',
"solution":'''namespace Challenge;public record Cart(decimal Subtotal,bool Vip,string Coupon);public interface IPromotion{decimal Apply(Cart cart,decimal current);}public sealed class PricingEngine(IEnumerable<IPromotion> rules){readonly IReadOnlyList<IPromotion> all=rules.ToList();public decimal Total(Cart cart){var value=all.Aggregate(cart.Subtotal,(v,r)=>r.Apply(cart,v));return Math.Max(0,value);}}''',
"public":'''using Challenge;if(new PricingEngine([]).Total(new(10,false,""))!=10)throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}C("C01",()=>new PricingEngine([new Add(3)]).Total(new(10,false,""))==13);C("C02",()=>new PricingEngine([new Mul(2),new Add(3)]).Total(new(10,false,""))==23);C("C03",()=>new PricingEngine([new Add(-50)]).Total(new(10,false,""))==0);C("C04",()=>new PricingEngine([new Mul(.5m)]).Total(new(10,false,""))==5);C("C05",()=>new PricingEngine([]).Total(new(7,false,""))==7);class Add(decimal n):IPromotion{public decimal Apply(Cart c,decimal v)=>v+n;}class Mul(decimal n):IPromotion{public decimal Apply(Cart c,decimal v)=>v*n;}'''
},
{
"id":"15","context":"uma suíte de autenticação que falha intermitentemente. Tokens dependem de relógio e gerador de identificadores controláveis.",
"situation":"Torne `TokenService` determinístico e seguro para testes paralelos usando as abstrações já fornecidas.",
"expected":"O prazo deve vir de `IClock`, o nonce de `INonceSource` e chamadas concorrentes não podem compartilhar estado mutável.",
"intent":"Avaliar diagnóstico de flakiness e design para testabilidade.","cause":"o serviço usa relógio real e `Random.Shared`, ignorando dependências.","trap":"desligar paralelismo, adicionar retry ou espera.","notes":"A referência é stateless e deriva toda entrada não determinística das dependências injetadas.",
"criteria":[("C01","mínimo",3,"expiração usa o relógio injetado"),("C02","mínimo",2,"nonce usa a fonte injetada"),("C03","mínimo",2,"mesmas dependências geram resultado reproduzível"),("C04","intermediário",2,"instâncias não compartilham estado"),("C05","desejado",1,"código não usa relógio ou Random globais")],
"broken":'''namespace Challenge;public interface IClock{DateTimeOffset UtcNow{get;}}public interface INonceSource{string Next();}public record Token(string User,DateTimeOffset ExpiresAt,string Nonce);public sealed class TokenService(IClock clock,INonceSource nonce){public IClock ConfiguredClock=>clock;public INonceSource ConfiguredNonce=>nonce;public Token Create(string user,TimeSpan ttl)=>new(user,DateTimeOffset.UtcNow+ttl,Random.Shared.Next().ToString());}''',
"solution":'''namespace Challenge;public interface IClock{DateTimeOffset UtcNow{get;}}public interface INonceSource{string Next();}public record Token(string User,DateTimeOffset ExpiresAt,string Nonce);public sealed class TokenService(IClock clock,INonceSource nonce){public Token Create(string user,TimeSpan ttl)=>new(user,clock.UtcNow+ttl,nonce.Next());}''',
"public":'''using Challenge;var t=new TokenService(new C(),new N()).Create("u",TimeSpan.FromMinutes(1));if(t.User!="u")throw new Exception();Console.WriteLine("Public tests passed");class C:IClock{public DateTimeOffset UtcNow=>DateTimeOffset.UnixEpoch;}class N:INonceSource{public string Next()=>"n";}''',
"hidden":'''using Challenge;void Ck(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}var at=DateTimeOffset.Parse("2030-01-01T00:00:00Z");Ck("C01",()=>new TokenService(new Clock(at),new Nonce("x")).Create("u",TimeSpan.FromHours(1)).ExpiresAt==at.AddHours(1));Ck("C02",()=>new TokenService(new Clock(at),new Nonce("fixed")).Create("u",TimeSpan.Zero).Nonce=="fixed");Ck("C03",()=>new TokenService(new Clock(at),new Nonce("x")).Create("u",TimeSpan.Zero)==new TokenService(new Clock(at),new Nonce("x")).Create("u",TimeSpan.Zero));Ck("C04",()=>new TokenService(new Clock(at),new Nonce("a")).Create("u",TimeSpan.Zero).Nonce!="b");Ck("C05",()=>true);class Clock(DateTimeOffset x):IClock{public DateTimeOffset UtcNow=>x;}class Nonce(string x):INonceSource{public string Next()=>x;}''',
"static":[{"id":"C05","forbid":"DateTime(Offset)?\\.UtcNow|Random\\.Shared"}]
},
{
"id":"16","context":"a listagem compartilhada por uma API e um cliente web. O cursor contém data e ID para desempatar registros.",
"situation":"Itens com a mesma data são repetidos ou omitidos entre páginas. Implemente ordenação `(CreatedAt desc, Id asc)` e cursor exclusivo sobre os dois campos.",
"expected":"`Page` deve retornar no máximo `take` itens, rejeitar limites inválidos e manter continuidade determinística.",
"intent":"Avaliar correção de regressão em contrato de paginação e ordenação estável.","cause":"o filtro do cursor considera apenas a data.","trap":"deduplicar no cliente ou usar índice da lista como cursor.","notes":"A referência ordena por data descendente e ID ascendente e aplica comparação lexicográfica exclusiva.",
"criteria":[("C01","mínimo",3,"itens aparecem uma única vez entre páginas"),("C02","mínimo",2,"empates usam ID ascendente"),("C03","mínimo",2,"cursor é exclusivo"),("C04","intermediário",2,"entrada desordenada gera saída estável"),("C05","desejado",1,"take inválido é rejeitado")],
"broken":'''namespace Challenge;public record Item(string Id,DateTimeOffset CreatedAt);public static class Paginator{public static IReadOnlyList<Item> Page(IEnumerable<Item> items,DateTimeOffset? after,string? afterId,int take)=>items.Where(x=>after is null||x.CreatedAt<after).OrderByDescending(x=>x.CreatedAt).Take(take).ToList();}''',
"solution":'''namespace Challenge;public record Item(string Id,DateTimeOffset CreatedAt);public static class Paginator{public static IReadOnlyList<Item> Page(IEnumerable<Item> items,DateTimeOffset? after,string? afterId,int take){if(take<=0)throw new ArgumentOutOfRangeException(nameof(take));return items.Where(x=>after is null||x.CreatedAt<after||(x.CreatedAt==after&&string.CompareOrdinal(x.Id,afterId)>0)).OrderByDescending(x=>x.CreatedAt).ThenBy(x=>x.Id,StringComparer.Ordinal).Take(take).ToList();}}''',
"public":'''using Challenge;var t=DateTimeOffset.UtcNow;if(Paginator.Page([new("a",t)],null,null,10).Single().Id!="a")throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}var t=DateTimeOffset.Parse("2025-01-01T00:00:00Z");var all=new[]{new Item("c",t),new Item("a",t),new Item("b",t),new Item("d",t.AddDays(-1))};C("C01",()=>{var a=Paginator.Page(all,null,null,2);var b=Paginator.Page(all,a[^1].CreatedAt,a[^1].Id,2);return a.Concat(b).Select(x=>x.Id).Distinct().Count()==4;});C("C02",()=>string.Join(',',Paginator.Page(all,null,null,3).Select(x=>x.Id))=="a,b,c");C("C03",()=>Paginator.Page(all,t,"b",5).First().Id=="c");C("C04",()=>Paginator.Page(all.Reverse(),null,null,4).Select(x=>x.Id).SequenceEqual(["a","b","c","d"]));C("C05",()=>{try{Paginator.Page(all,null,null,0);return false;}catch(ArgumentOutOfRangeException){return true;}});'''
},
{
"id":"17","context":"uma listagem de catálogo cujo repositório registra quantas consultas simuladas foram feitas.",
"situation":"Eliminar o padrão N+1: `CatalogService.List` deve carregar produtos e disponibilidades em no máximo duas consultas, mantendo paginação e valores.",
"expected":"Use a operação em lote do repositório e não um cache global.",
"intent":"Avaliar diagnóstico de I/O repetitivo e correção mensurável de query.","cause":"há uma consulta de estoque por produto.","trap":"trocar N+1 por estado global ou remover campos da resposta.","notes":"A referência busca a página de produtos e uma tabela de estoques para os IDs da página.",
"criteria":[("C01","mínimo",3,"valores retornados estão corretos"),("C02","mínimo",3,"no máximo duas consultas são executadas"),("C03","mínimo",2,"paginação limita os produtos"),("C04","intermediário",1,"produto sem estoque retorna zero"),("C05","desejado",1,"chamada seguinte observa atualização do repositório")],
"broken":'''namespace Challenge;public record Product(string Id,string Name);public record View(string Id,string Name,int Stock);public sealed class CatalogRepository(List<Product> products,Dictionary<string,int> stock){public int QueryCount;public IReadOnlyList<Product> Products(int skip,int take){QueryCount++;return products.Skip(skip).Take(take).ToList();}public int Stock(string id){QueryCount++;return stock.GetValueOrDefault(id);}public IReadOnlyDictionary<string,int> Stocks(IEnumerable<string> ids){QueryCount++;return ids.ToDictionary(x=>x,x=>stock.GetValueOrDefault(x));}public void Set(string id,int n)=>stock[id]=n;}
public sealed class CatalogService(CatalogRepository repo){public IReadOnlyList<View> List(int skip,int take)=>repo.Products(skip,take).Select(x=>new View(x.Id,x.Name,repo.Stock(x.Id))).ToList();}''',
"solution":'''namespace Challenge;public record Product(string Id,string Name);public record View(string Id,string Name,int Stock);public sealed class CatalogRepository(List<Product> products,Dictionary<string,int> stock){public int QueryCount;public IReadOnlyList<Product> Products(int skip,int take){QueryCount++;return products.Skip(skip).Take(take).ToList();}public int Stock(string id){QueryCount++;return stock.GetValueOrDefault(id);}public IReadOnlyDictionary<string,int> Stocks(IEnumerable<string> ids){QueryCount++;return ids.ToDictionary(x=>x,x=>stock.GetValueOrDefault(x));}public void Set(string id,int n)=>stock[id]=n;}
public sealed class CatalogService(CatalogRepository repo){public IReadOnlyList<View> List(int skip,int take){var products=repo.Products(skip,take);var stocks=repo.Stocks(products.Select(x=>x.Id));return products.Select(x=>new View(x.Id,x.Name,stocks.GetValueOrDefault(x.Id))).ToList();}}''',
"public":'''using Challenge;var r=new CatalogRepository([new("a","A")],new(){{"a",2}});if(new CatalogService(r).List(0,1).Single().Stock!=2)throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;void C(string id,Func<bool> f){try{Console.WriteLine($"{id}|{(f()?"pass":"fail")}");}catch{Console.WriteLine($"{id}|fail");}}CatalogRepository R()=>new([new("a","A"),new("b","B"),new("c","C")],new(){{"a",1},{"b",2}});C("C01",()=>new CatalogService(R()).List(0,3).Select(x=>x.Stock).SequenceEqual([1,2,0]));C("C02",()=>{var r=R();new CatalogService(r).List(0,3);return r.QueryCount<=2;});C("C03",()=>new CatalogService(R()).List(1,1).Single().Id=="b");C("C04",()=>new CatalogService(R()).List(2,1).Single().Stock==0);C("C05",()=>{var r=R();var s=new CatalogService(r);s.List(0,1);r.Set("a",9);return s.List(0,1).Single().Stock==9;});'''
},
{
"id":"18","context":"a exportação CSV de milhões de eventos. A fonte é assíncrona e contabiliza leituras para permitir testes sem medir memória de forma frágil.",
"situation":"Produza linhas progressivamente: antes do primeiro `yield`, no máximo um item pode ter sido lido. Propague cancelamento e faça escaping CSV.",
"expected":"`Export` deve permanecer um `IAsyncEnumerable<string>` e não acumular o conjunto completo.",
"intent":"Avaliar streaming, backpressure, escaping e cancelamento.","cause":"a implementação materializa toda a fonte antes de começar a produzir.","trap":"paginar a leitura e ainda acumular todas as strings.","notes":"A referência usa `await foreach`, verifica cancelamento e emite cada linha assim que o item chega.",
"criteria":[("C01","mínimo",3,"todas as linhas são emitidas na ordem"),("C02","mínimo",3,"primeira linha não exige leitura integral"),("C03","mínimo",2,"campos CSV recebem escaping"),("C04","intermediário",1,"cancelamento interrompe enumeração"),("C05","desejado",1,"fonte vazia é suportada")],
"broken":'''using System.Runtime.CompilerServices;namespace Challenge;public record Row(string Id,string Name);public static class Exporter{public static async IAsyncEnumerable<string> Export(IAsyncEnumerable<Row> source,[EnumeratorCancellation]CancellationToken ct=default){var all=new List<Row>();await foreach(var x in source.WithCancellation(ct))all.Add(x);foreach(var x in all)yield return $"{x.Id},{x.Name}";}}''',
"solution":'''using System.Runtime.CompilerServices;namespace Challenge;public record Row(string Id,string Name);public static class Exporter{static string Csv(string x){if(x.IndexOfAny([',',(char)34,'\\n','\\r'])<0)return x;var q=((char)34).ToString();return q+x.Replace(q,q+q)+q;}public static async IAsyncEnumerable<string> Export(IAsyncEnumerable<Row> source,[EnumeratorCancellation]CancellationToken ct=default){await foreach(var x in source.WithCancellation(ct)){ct.ThrowIfCancellationRequested();yield return $"{Csv(x.Id)},{Csv(x.Name)}";}}}''',
"public":'''using Challenge;async IAsyncEnumerable<Row> S(){yield return new("1","A");}var a=new List<string>();await foreach(var x in Exporter.Export(S()))a.Add(x);if(a.Single()!="1,A")throw new Exception();Console.WriteLine("Public tests passed");''',
"hidden":'''using Challenge;void P(string id,bool ok)=>Console.WriteLine($"{id}|{(ok?"pass":"fail")}");async IAsyncEnumerable<Row> S(Counter c,int n){for(int i=0;i<n;i++){c.N++;await Task.Yield();yield return new(i.ToString(),i==0?"A,B":"N");}}var c1=new Counter();var out1=new List<string>();await foreach(var x in Exporter.Export(S(c1,3)))out1.Add(x);P("C01",out1.Count==3&&out1[2]=="2,N");var c2=new Counter();await using(var e=Exporter.Export(S(c2,100)).GetAsyncEnumerator()){await e.MoveNextAsync();P("C02",c2.N<=1);}var q=(char)34;P("C03",out1[0]==$"0,{q}A,B{q}");var cts=new CancellationTokenSource();cts.Cancel();try{await foreach(var x in Exporter.Export(S(new(),3),cts.Token)){}P("C04",false);}catch(OperationCanceledException){P("C04",true);}var empty=0;await foreach(var x in Exporter.Export(S(new(),0)))empty++;P("C05",empty==0);class Counter{public int N;}'''
}
]

if __name__ == "__main__":
    for case in CASES:
        dotnet_case(case)
    print(f"Generated {len(CASES)} .NET exercises")
