#!/usr/bin/env python3
"""Definitions for the production-sized exercise expansion (101-130)."""


def backend(id, slug, title, focus, summary, body, cases):
    return dict(id=id, slug=slug, title=title, focus=focus, summary=summary, body=body, cases=cases)


def frontend(id, slug, title, framework, focus, summary, body, cases):
    return dict(id=id, slug=slug, title=title, framework=framework, focus=focus, summary=summary, body=body, cases=cases)


BACKEND = [
backend("101", "purchase-approval-workflow", "Fluxo de aprovação de compras", "workflow de domínio", "Uma plataforma de compras precisa decidir a próxima etapa usando valor, centro de custo e segregação de funções.", '''var p=input.Split('|');var amount=decimal.Parse(p[0],CultureInfo.InvariantCulture);var requester=p[1];var approver=p[2];var budget=p[3]=="yes";if(!budget)return"budget-rejected";if(requester==approver)return"segregation-required";return amount>=10000m?"director-approval":amount>=1000m?"manager-approval":"approved";''', [("compra pequena é aprovada", "500|ana|bia|yes", "approved"), ("valor médio exige gerente", "1000|ana|bia|yes", "manager-approval"), ("alto valor exige diretor", "10000|ana|bia|yes", "director-approval"), ("sem orçamento rejeita", "100|ana|bia|no", "budget-rejected"), ("autor não aprova a própria compra", "100|ana|ana|yes", "segregation-required")]),
backend("102", "refund-ledger-invariants", "Estorno no razão contábil", "invariantes contábeis", "Um estorno deve produzir lançamentos de sinal oposto, na moeda original, sem alterar o lançamento histórico.", '''var p=input.Split('|');var amount=decimal.Parse(p[0],CultureInfo.InvariantCulture);var kind=p[1];var currency=p[2].ToUpperInvariant();var reversed=kind=="debit"?"credit":"debit";return $"{reversed}|{amount.ToString("0.00",CultureInfo.InvariantCulture)}|{currency}";''', [("débito vira crédito", "25.5|debit|brl", "credit|25.50|BRL"), ("crédito vira débito", "10|credit|USD", "debit|10.00|USD"), ("centavos são preservados", "0.01|debit|EUR", "credit|0.01|EUR"), ("valor não muda de sinal", "99.99|credit|brl", "debit|99.99|BRL"), ("moeda é normalizada", "1|debit|gbp", "credit|1.00|GBP")]),
backend("103", "regional-config-precedence", "Precedência de configuração regional", "configuração", "A aplicação combina configuração global, regional e de tenant sem deixar valor vazio sobrescrever uma configuração válida.", '''var p=input.Split('|');return new[]{p[2],p[1],p[0]}.FirstOrDefault(x=>!string.IsNullOrWhiteSpace(x))??"unset";''', [("tenant vence", "global|regional|tenant", "tenant"), ("regional cobre tenant vazio", "global|regional|", "regional"), ("global é fallback", "global||", "global"), ("espaço não sobrescreve", "global|regional|   ", "regional"), ("tudo ausente é unset", "||", "unset")]),
backend("104", "audit-history-reconstruction", "Reconstrução de histórico de auditoria", "dados temporais", "Consultas históricas precisam reconstruir o valor vigente em um instante, mesmo quando eventos chegam fora de ordem.", '''var p=input.Split('|');var at=long.Parse(p[0]);var events=p[1].Split(',',StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Split(':')).Select(x=>(At:long.Parse(x[0]),Value:x[1])).Where(x=>x.At<=at).OrderBy(x=>x.At).ToArray();return events.Length==0?"missing":events[^1].Value;''', [("usa último evento anterior", "20|10:draft,20:open,30:closed", "open"), ("ordena eventos recebidos fora de ordem", "25|20:open,30:closed,10:draft", "open"), ("antes da criação é ausente", "5|10:draft", "missing"), ("evento na borda vale", "10|10:draft", "draft"), ("sem eventos é ausente", "10|", "missing")]),
backend("105", "shipment-allocation", "Alocação de remessas", "algoritmos de domínio", "Pedidos devem ser alocados ao depósito com estoque suficiente e menor distância, usando ID como desempate estável.", '''var p=input.Split('|');var needed=int.Parse(p[0]);var candidates=p[1].Split(',',StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Split(':')).Select(x=>(Id:x[0],Stock:int.Parse(x[1]),Distance:int.Parse(x[2]))).Where(x=>x.Stock>=needed).OrderBy(x=>x.Distance).ThenBy(x=>x.Id,StringComparer.Ordinal).ToArray();return candidates.Length==0?"unavailable":candidates[0].Id;''', [("menor distância vence", "2|a:5:20,b:5:10", "b"), ("estoque insuficiente é ignorado", "5|a:4:1,b:5:9", "b"), ("ID desempata", "1|b:2:5,a:2:5", "a"), ("nenhum candidato", "10|a:2:1", "unavailable"), ("lista vazia", "1|", "unavailable")]),
backend("106", "notification-digest", "Agrupamento de notificações", "processamento em lote", "Um job de digest agrupa notificações por destinatário e canal, remove duplicatas e preserva ordem determinística.", '''var rows=input.Split(',',StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Split(':')).Select(x=>$"{x[0]}:{x[1]}:{x[2]}").Distinct().OrderBy(x=>x.Split(':')[0]).ThenBy(x=>x.Split(':')[1]);return string.Join(',',rows);''', [("agrupa em ordem estável", "b:email:2,a:sms:1", "a:sms:1,b:email:2"), ("remove duplicata", "a:email:1,a:email:1", "a:email:1"), ("canais ficam separados", "a:sms:1,a:email:2", "a:email:2,a:sms:1"), ("destinatários ficam separados", "b:email:1,a:email:1", "a:email:1,b:email:1"), ("vazio produz vazio", "", "")]),
backend("107", "legal-hold-retention", "Retenção com bloqueio legal", "compliance", "A limpeza de documentos deve respeitar prazo, bloqueio legal e estado de exclusão já concluída.", '''var p=input.Split('|');var age=int.Parse(p[0]);var retention=int.Parse(p[1]);if(p[2]=="hold")return"keep";if(p[3]=="deleted")return"skip";return age>=retention?"delete":"keep";''', [("expirado é removido", "365|365|none|active", "delete"), ("novo é mantido", "10|365|none|active", "keep"), ("hold prevalece", "900|365|hold|active", "keep"), ("já removido é ignorado", "900|365|none|deleted", "skip"), ("um dia antes mantém", "364|365|none|active", "keep")]),
backend("108", "dual-key-secret-rotation", "Rotação de segredo sem indisponibilidade", "gestão de segredos", "Durante uma rotação, assinaturas feitas com a chave atual ou anterior são aceitas, mas chaves retiradas não podem voltar.", '''var p=input.Split('|');var presented=p[0];var current=p[1];var previous=p[2];return CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(presented),Encoding.UTF8.GetBytes(current))||(!string.IsNullOrEmpty(previous)&&CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(presented),Encoding.UTF8.GetBytes(previous)))?"valid":"invalid";''', [("chave atual vale", "k2|k2|k1", "valid"), ("chave anterior vale na janela", "k1|k2|k1", "valid"), ("chave antiga demais falha", "k0|k2|k1", "invalid"), ("anterior vazia não aceita vazio", "|k2|", "invalid"), ("comparação é exata", "K2|k2|k1", "invalid")]),
backend("109", "readiness-dependencies", "Readiness de dependências", "observabilidade", "O endpoint de readiness deve distinguir dependências obrigatórias das opcionais e não confundir liveness com prontidão.", '''var states=input.Split(',',StringSplitOptions.RemoveEmptyEntries);var required=states.Where(x=>x.StartsWith("required:"));return required.All(x=>x.EndsWith(":up"))?"ready":"not-ready";''', [("todas obrigatórias disponíveis", "required:db:up,required:queue:up", "ready"), ("banco indisponível bloqueia", "required:db:down,required:queue:up", "not-ready"), ("opcional não bloqueia", "required:db:up,optional:analytics:down", "ready"), ("sem dependências obrigatórias", "optional:x:down", "ready"), ("lista vazia", "", "ready")]),
backend("110", "percentage-feature-rollout", "Rollout percentual de feature", "entrega progressiva", "Uma feature deve ser atribuída de forma determinística por usuário, respeitando percentuais zero e cem.", '''var p=input.Split('|');var percent=int.Parse(p[1]);if(percent<=0)return"off";if(percent>=100)return"on";var bucket=p[0].Aggregate(0,(h,c)=>(h*31+c)%100);return bucket<percent?"on":"off";''', [("zero desliga", "ana|0", "off"), ("cem liga", "ana|100", "on"), ("bucket abaixo liga", "a|98", "on"), ("bucket na borda desliga", "a|97", "off"), ("mesmo usuário é estável", "b|99", "on")]),
backend("111", "background-job-drain", "Encerramento gracioso de workers", "lifecycle", "Ao receber shutdown, o worker para de aceitar itens e aguarda somente o trabalho em andamento até o prazo.", '''var p=input.Split('|');var active=int.Parse(p[0]);var queued=int.Parse(p[1]);var remaining=int.Parse(p[2]);if(remaining<=0&&active>0)return"force-stop";if(active>0)return$"drain:{active}";return queued>0?"leave-queued":"stopped";''', [("trabalho ativo drena", "2|5|30", "drain:2"), ("prazo encerra à força", "1|0|0", "force-stop"), ("fila não é iniciada", "0|3|30", "leave-queued"), ("sem trabalho para", "0|0|30", "stopped"), ("ativo ignora fila nova", "1|99|5", "drain:1")]),
backend("112", "ordered-parallel-fanout", "Fan-out paralelo ordenado", "concorrência", "Resultados de chamadas paralelas precisam manter a ordem de entrada e registrar falhas por item sem abortar o lote.", '''var rows=input.Split(',',StringSplitOptions.RemoveEmptyEntries).Select((x,i)=>x.StartsWith("fail:")?$"{i}:error:{x[5..]}":$"{i}:ok:{x}");return string.Join(',',rows);''', [("ordem é preservada", "slow,fast", "0:ok:slow,1:ok:fast"), ("falha é localizada", "a,fail:b,c", "0:ok:a,1:error:b,2:ok:c"), ("todas falham", "fail:a,fail:b", "0:error:a,1:error:b"), ("um item", "x", "0:ok:x"), ("vazio", "", "")]),
backend("113", "api-sunset-policy", "Descontinuação de API", "governança de API", "Versões depreciadas devem emitir Deprecation e Sunset coerentes sem marcar versões ainda suportadas.", '''var p=input.Split('|');var version=int.Parse(p[0]);var current=int.Parse(p[1]);var sunset=p[2];return version<current?$"deprecated|sunset={sunset}":"supported";''', [("versão antiga deprecia", "1|2|2030-01-01", "deprecated|sunset=2030-01-01"), ("versão atual suporta", "2|2|2030-01-01", "supported"), ("versão futura suporta", "3|2|2030-01-01", "supported"), ("sunset é preservado", "1|4|2028-12-31", "deprecated|sunset=2028-12-31"), ("primeira versão atual", "1|1|never", "supported")]),
backend("114", "trace-baggage-allowlist", "Privacidade em baggage de tracing", "telemetria", "Propagação de tracing deve manter somente chaves permitidas, limitar tamanho e ordenar a saída.", '''var allowed=new HashSet<string>{"tenant","request-type","region"};var rows=input.Split(',',StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Split('=',2)).Where(x=>allowed.Contains(x[0])&&x[1].Length<=20).OrderBy(x=>x[0]).Select(x=>$"{x[0]}={x[1]}");return string.Join(',',rows);''', [("mantém allowlist", "tenant=t1,region=br", "region=br,tenant=t1"), ("remove segredo", "tenant=t1,token=abc", "tenant=t1"), ("remove valor longo", "tenant=abcdefghijklmnopqrstuvwxyz", ""), ("ordena chaves", "tenant=t,request-type=r,region=x", "region=x,request-type=r,tenant=t"), ("vazio", "", "")]),
backend("115", "deadlock-retry-classifier", "Classificação de retry de banco", "persistência resiliente", "A camada de dados deve repetir somente deadlocks transitórios e nunca violações permanentes ou tentativas já esgotadas.", '''var p=input.Split('|');var code=p[0];var attempt=int.Parse(p[1]);var max=int.Parse(p[2]);return code=="deadlock"&&attempt<max?"retry":code=="deadlock"?"exhausted":"fail";''', [("deadlock repete", "deadlock|1|3", "retry"), ("última tentativa esgota", "deadlock|3|3", "exhausted"), ("unique não repete", "unique|1|3", "fail"), ("timeout não é assumido", "timeout|1|3", "fail"), ("zero tentativas ainda repete", "deadlock|0|1", "retry")]),
]


FRONTEND = [
frontend("116", "permission-aware-navigation", "Navegação orientada por permissões", "react", "autorização de interface", "O menu deve ocultar ações indisponíveis sem usar isso como substituto da autorização do servidor.", '''const[permissions,routes]=input.split("|");const set=new Set(permissions.split(",").filter(Boolean));return routes.split(",").filter(Boolean).filter(x=>{const[r,p]=x.split("=");return !p||set.has(p)}).map(x=>x.split("=")[0]).join(",")''', [("mostra rota permitida", "orders:read|home=,orders=orders:read", "home,orders"), ("oculta rota negada", "|home=,admin=admin:read", "home"), ("múltiplas permissões", "a,b|one=a,two=b", "one,two"), ("rota pública permanece", "x|public=,private=y", "public"), ("lista vazia", "x|", "")]),
frontend("117", "undo-redo-history", "Histórico de undo e redo", "angular", "estado reversível", "Um editor precisa calcular corretamente o estado após comandos, undo, redo e nova edição que invalida o futuro.", '''const cmds=input.split(",").filter(Boolean);let value="",undo=[],redo=[];for(const c of cmds){if(c==="undo"&&undo.length){redo.push(value);value=undo.pop()}else if(c==="redo"&&redo.length){undo.push(value);value=redo.pop()}else if(c.startsWith("set:")){undo.push(value);value=c.slice(4);redo=[]}}return value||"empty"''', [("undo restaura", "set:a,set:b,undo", "a"), ("redo reaplica", "set:a,set:b,undo,redo", "b"), ("nova edição limpa redo", "set:a,set:b,undo,set:c,redo", "c"), ("undo vazio é seguro", "undo", "empty"), ("vários undos", "set:a,set:b,set:c,undo,undo", "a")]),
frontend("118", "autosave-draft-versioning", "Autosave versionado", "react", "persistência de rascunho", "O autosave deve ignorar respostas antigas e distinguir conflito de versão de falha de rede.", '''const[current,response,status]=input.split("|").map((x,i)=>i<2?Number(x):x);if(status==="conflict")return"resolve";if(status==="network")return"retry";return response===current?"apply":"ignore"''', [("resposta atual aplica", "3|3|ok", "apply"), ("resposta antiga ignora", "3|2|ok", "ignore"), ("resposta futura ignora", "3|4|ok", "ignore"), ("conflito abre resolução", "3|3|conflict", "resolve"), ("rede agenda retry", "3|3|network", "retry")]),
frontend("119", "wizard-restoration", "Restauração de wizard", "angular", "formulários multietapa", "Um fluxo multietapa deve restaurar somente etapas válidas e nunca pular uma etapa obrigatória incompleta.", '''const[saved0,valid]=input.split("|");const saved=Math.max(0,Number(saved0));const flags=valid.split(",").map(x=>x==="yes");let firstInvalid=flags.findIndex(x=>!x);if(firstInvalid<0)firstInvalid=flags.length;return String(Math.min(saved,firstInvalid))''', [("restaura etapa válida", "1|yes,no,no", "1"), ("não pula primeira inválida", "2|no,no,no", "0"), ("limita na inválida", "3|yes,yes,no,yes", "2"), ("todas válidas permitem fim", "3|yes,yes,yes", "3"), ("índice negativo vira zero", "-1|yes", "0")]),
frontend("120", "accessible-chart-summary", "Resumo acessível de gráfico", "react", "visualização acessível", "Um gráfico precisa produzir alternativa textual com tendência, mínimo e máximo a partir dos mesmos dados visuais.", '''const values=input.split(",").filter(Boolean).map(Number);if(!values.length)return"empty";const trend=values.at(-1)>values[0]?"up":values.at(-1)<values[0]?"down":"flat";return`${trend}|min=${Math.min(...values)}|max=${Math.max(...values)}`''', [("tendência de alta", "1,3,5", "up|min=1|max=5"), ("tendência de baixa", "5,3,1", "down|min=1|max=5"), ("estável", "2,5,2", "flat|min=2|max=5"), ("um ponto", "7", "flat|min=7|max=7"), ("sem dados", "", "empty")]),
frontend("121", "reduced-motion-policy", "Preferência por movimento reduzido", "angular", "acessibilidade visual", "Transições precisam respeitar prefers-reduced-motion mantendo feedback sem animação contínua.", '''const[preference,effect]=input.split("|");if(preference==="reduce")return effect==="progress"?"static-progress":"instant";return effect==="progress"?"animated-progress":"animate"''', [("reduce remove transição", "reduce|modal", "instant"), ("reduce mantém progresso estático", "reduce|progress", "static-progress"), ("normal anima modal", "normal|modal", "animate"), ("normal anima progresso", "normal|progress", "animated-progress"), ("efeito desconhecido respeita reduce", "reduce|sparkle", "instant")]),
frontend("122", "localized-decimal-input", "Entrada decimal localizada", "react", "internacionalização", "Valores monetários digitados com separadores locais precisam virar representação canônica sem ambiguidades.", '''const[locale,raw]=input.split("|");const text=raw.trim();const normalized=locale==="pt-BR"?text.replaceAll(".","").replace(",","."):text.replaceAll(",","");const n=Number(normalized);return Number.isFinite(n)?n.toFixed(2):"invalid"''', [("pt-BR converte vírgula", "pt-BR|1.234,56", "1234.56"), ("en-US converte agrupamento", "en-US|1,234.56", "1234.56"), ("inteiro recebe centavos", "pt-BR|10", "10.00"), ("texto inválido", "en-US|abc", "invalid"), ("espaços são aceitos", "pt-BR| 2,5 ", "2.50")]),
frontend("123", "stable-form-array-identity", "Identidade estável em formulários", "angular", "formulários dinâmicos", "Linhas adicionadas e removidas devem preservar IDs estáveis para não trocar foco nem estado de validação.", '''const[ids,command]=input.split("|");const rows=ids.split(",").filter(Boolean);const[action,id,pos]=command.split(":");if(action==="remove")return rows.filter(x=>x!==id).join(",");if(action==="add"&&!rows.includes(id)){rows.splice(pos?Number(pos):rows.length,0,id)}return rows.join(",")''', [("remove por ID", "a,b,c|remove:b", "a,c"), ("adiciona ao fim", "a,b|add:c", "a,b,c"), ("adiciona na posição", "a,c|add:b:1", "a,b,c"), ("ID duplicado não entra", "a,b|add:b", "a,b"), ("remoção ausente não muda", "a,b|remove:x", "a,b")]),
frontend("124", "normalized-entity-cache", "Cache normalizado de entidades", "react", "gerenciamento de estado", "Atualizações parciais devem mesclar entidades por ID sem duplicar referências nas listas.", '''const[current,update]=input.split("|");const map=new Map(current.split(",").filter(Boolean).map(x=>{const[id,value]=x.split(":");return[id,value]}));const[id,value]=update.split(":");if(id)map.set(id,value);return[...map].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}:${v}`).join(",")''', [("atualiza entidade", "a:old,b:same|a:new", "a:new,b:same"), ("insere entidade", "a:one|b:two", "a:one,b:two"), ("ordena por ID", "b:two|a:one", "a:one,b:two"), ("vazio aceita primeira", "|a:one", "a:one"), ("valor vazio é mantido", "a:one|a:", "a:")]),
frontend("125", "ssr-feature-hydration", "Paridade de feature flags no SSR", "angular", "renderização híbrida", "Servidor e cliente precisam usar o mesmo snapshot de flags durante a hidratação para evitar reconstrução da árvore.", '''const[server,client]=input.split("|");const norm=x=>x.split(",").filter(Boolean).sort().join(",");return norm(server)===norm(client)?"hydrate":"rerender"''', [("snapshots iguais hidratam", "a,b|a,b", "hydrate"), ("ordem não importa", "a,b|b,a", "hydrate"), ("flag extra reconstrói", "a|a,b", "rerender"), ("flag ausente reconstrói", "a,b|a", "rerender"), ("dois vazios hidratam", "|", "hydrate")]),
frontend("126", "streaming-chunk-order", "Ordenação de chunks em streaming", "react", "renderização incremental", "Chunks de uma resposta podem chegar fora de ordem e só devem liberar o prefixo contínuo já disponível.", '''const[expected0,chunks]=input.split("|");let expected=Number(expected0),out=[];const map=new Map(chunks.split(",").filter(Boolean).map(x=>{const[i,v]=x.split(":");return[Number(i),v]}));while(map.has(expected)){out.push(map.get(expected));expected++}return out.length?`${expected}|${out.join("")}`:`${expected}|wait`''', [("primeiro chunk libera", "0|0:A", "1|A"), ("gap aguarda", "0|1:B", "0|wait"), ("fora de ordem completa prefixo", "0|1:B,0:A,2:C", "3|ABC"), ("continua de checkpoint", "2|2:C,3:D", "4|CD"), ("vazio aguarda", "4|", "4|wait")]),
frontend("127", "storage-quota-eviction", "Evicção por quota do navegador", "angular", "armazenamento local", "O cache local deve remover entradas menos recentes até caber, preservando itens fixados.", '''const[limit0,incoming0,entries]=input.split("|");let used=0;const rows=entries.split(",").filter(Boolean).map(x=>{const[id,size,age,pinned]=x.split(":");used+=Number(size);return{id,size:Number(size),age:Number(age),pinned:pinned==="yes"}});const incoming=Number(incoming0);const evicted=[];for(const r of rows.filter(x=>!x.pinned).sort((a,b)=>b.age-a.age)){if(used+incoming<=Number(limit0))break;used-=r.size;evicted.push(r.id)}return used+incoming<=Number(limit0)?evicted.join(",")||"none":"quota-error"''', [("cabe sem remover", "100|10|a:20:5:no", "none"), ("remove mais antigo", "50|20|a:20:9:no,b:20:1:no", "a"), ("remove até caber", "50|30|a:20:9:no,b:20:8:no,c:20:1:no", "a,b"), ("fixado é preservado", "30|20|a:20:9:yes", "quota-error"), ("vazio recebe item", "20|20|", "none")]),
frontend("128", "clipboard-fallback", "Fallback de área de transferência", "react", "integração com navegador", "A ação de copiar deve escolher API segura, fallback ou orientação manual conforme contexto e permissão.", '''const[secure,api,permission]=input.split("|");if(secure==="yes"&&api==="yes"&&permission!=="denied")return"clipboard-api";if(permission==="denied")return"manual";return"selection-fallback"''', [("API moderna em contexto seguro", "yes|yes|granted", "clipboard-api"), ("contexto inseguro usa fallback", "no|yes|granted", "selection-fallback"), ("API ausente usa fallback", "yes|no|prompt", "selection-fallback"), ("permissão negada orienta manual", "yes|yes|denied", "manual"), ("prompt ainda tenta API", "yes|yes|prompt", "clipboard-api")]),
frontend("129", "print-layout-pagination", "Paginação para impressão", "angular", "mídia impressa", "Relatórios impressos devem calcular quebras sem separar cabeçalho e primeira linha de uma seção.", '''const[page0,sections]=input.split("|");const page=Number(page0);let used=0,pages=1;for(const s of sections.split(",").filter(Boolean).map(Number)){if(s>page)return"oversize";if(used+s>page){pages++;used=0}used+=s}return String(pages)''', [("uma página", "100|20,30,40", "1"), ("quebra antes da seção", "100|60,50", "2"), ("múltiplas páginas", "50|30,30,30", "3"), ("seção do tamanho da página", "50|50,1", "2"), ("seção maior sinaliza", "50|51", "oversize")]),
frontend("130", "microfrontend-event-contract", "Contrato de eventos entre microfrontends", "react", "arquitetura frontend", "Eventos entre aplicações precisam validar versão, namespace e campos obrigatórios antes de atravessar a fronteira.", '''const[topic,version,payload]=input.split("|");if(!topic.startsWith("commerce."))return"foreign";if(version!=="v2")return"unsupported";const fields=new Set(payload.split(",").filter(Boolean));return fields.has("id")&&fields.has("timestamp")?"accept":"invalid"''', [("evento válido entra", "commerce.order|v2|id,timestamp,total", "accept"), ("namespace externo ignora", "profile.user|v2|id,timestamp", "foreign"), ("versão antiga rejeita", "commerce.order|v1|id,timestamp", "unsupported"), ("ID obrigatório", "commerce.order|v2|timestamp", "invalid"), ("timestamp obrigatório", "commerce.order|v2|id", "invalid")]),
]
